server:
  port: ${APP_PORT:8081}
  forward-headers-strategy: framework

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: ${KEYCLOAK_CLIENT_ID:sso-demo-app}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:L4sNRCgMwl2BTjMvqFtmugxxNlDLoPPA}
            authorization-grant-type: authorization_code
            redirect-uri: ${APP_REDIRECT_URI:https://placentate-forebodingly-charlotte.ngrok-free.dev/login/oauth2/code/{registrationId}}
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:https://keycloak-g9f2wog7auaqyvwqq9ti99gf.komoda.app/realms/sso-demo}
            authorization-uri: ${KEYCLOAK_AUTH_URI:https://keycloak-g9f2wog7auaqyvwqq9ti99gf.komoda.app/realms/sso-demo/protocol/openid-connect/auth}
            token-uri: ${KEYCLOAK_TOKEN_URI:https://keycloak-g9f2wog7auaqyvwqq9ti99gf.komoda.app/realms/sso-demo/protocol/openid-connect/token}
            jwk-set-uri: ${KEYCLOAK_JWK_URI:https://keycloak-g9f2wog7auaqyvwqq9ti99gf.komoda.app/realms/sso-demo/protocol/openid-connect/certs}
            user-info-uri: ${KEYCLOAK_USERINFO_URI:https://keycloak-g9f2wog7auaqyvwqq9ti99gf.komoda.app/realms/sso-demo/protocol/openid-connect/userinfo}
            user-name-attribute: preferred_username
